include: package:flutter_lints/flutter.yaml


analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
# - cancel_subscriptions
# - strict-casts: true
# - strict-inference: true
# - strict-raw-types: true
# - always_declare_return_types
# - cancel_subscriptions
# - close_sinks
# - comment_references
# - one_member_abstracts
# - only_throw_errors
# - package_api_docs
# - prefer_final_in_for_each
# - prefer_single_quotes
# - hash_and_equals
# - no_duplicate_case_values
# - always_put_control_body_on_new_line
# - always_put_required_named_parameters_first
# - always_require_non_null_named_parameters
# - always_specify_types
# - annotate_overrides
# - avoid_bool_literals_in_conditional_expressions
# - avoid_escaping_inner_quotes

