// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvYf7IG6RKdMr6xrniEZWlT71MdTwaRxk',
    appId: '1:130254661768:android:8ea535fc850c3ace57173d',
    messagingSenderId: '130254661768',
    projectId: 'crypto-list-app-36051',
    storageBucket: 'crypto-list-app-36051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLvrku2NiXlLvUi16PrqFxLisZl5R8L-A',
    appId: '1:130254661768:ios:2dfff5688b13ec4557173d',
    messagingSenderId: '130254661768',
    projectId: 'crypto-list-app-36051',
    storageBucket: 'crypto-list-app-36051.appspot.com',
    iosClientId: '130254661768-4kmjmrns0epgjpkpabmh80iub4mnts7g.apps.googleusercontent.com',
    iosBundleId: 'com.rebuscorp.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLvrku2NiXlLvUi16PrqFxLisZl5R8L-A',
    appId: '1:130254661768:ios:e7a8c399d6ec168a57173d',
    messagingSenderId: '130254661768',
    projectId: 'crypto-list-app-36051',
    storageBucket: 'crypto-list-app-36051.appspot.com',
    iosClientId: '130254661768-b1btpcp2vd84hh7urm9khdco7psf7bcn.apps.googleusercontent.com',
    iosBundleId: 'com.rebuscorp.learningFlutter.RunnerTests',
  );
}
